# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00fa926b3acb7946dfe20e08f3d8e03acda328e8fde4fb3504687b1db5505f7334c6a9bae56d5214d349d87fb15dbcd185d201cc991dc9db28ec5fc389cddc6b

test:
  secret_key_base: 6c6c441df6d7ea68f1270e2d444c2fd2acb37ce6fe22a3a016e0a4427398008eefa0c7f210125be8f03abaa12c455e8108e82f0872448fe5a15a60cb87478021

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
